# Generated by Django 5.2.17 on 2026-08-17 17:35

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_enable_pgvector"),
        ('companies', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Toàn thời gian'), ('PART_TIME', 'Bán thời gian'), ('INTERNSHIP', 'Thực tập'), ('CONTRACT', 'Hợp đồng'), ('REMOTE', 'Từ xa')], default='FULL_TIME', max_length=20)),
                ('experience_level', models.CharField(blank=True, choices=[('INTERN', 'Thực tập sinh'), ('FRESHER', 'Mới tốt nghiệp'), ('JUNIOR', 'Junior'), ('MIDDLE', 'Middle'), ('SENIOR', 'Senior'), ('LEAD', 'Lead / Manager')], max_length=20)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_negotiable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang tuyển'), ('CLOSED', 'Đã đóng'), ('EXPIRED', 'Hết hạn')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('raw_jd_file', models.FileField(blank=True, null=True, upload_to='job_descriptions/%Y/%m/')),
                ('raw_extracted_json', models.JSONField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('embedding_updated_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='companies.company')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'EMPLOYER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_posts',
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True, help_text="False = 'nice to have'")),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('min_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.jobpost')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_links', to='skills.skill')),
            ],
            options={
                'db_table': 'job_skills',
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='required_skills',
            field=models.ManyToManyField(related_name='job_posts', through='jobs.JobSkill', to='skills.skill'),
        ),
        migrations.AddConstraint(
            model_name='jobskill',
            constraint=models.UniqueConstraint(fields=('job', 'skill'), name='uniq_job_skill'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status'], name='job_posts_status_3d6f59_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['job_type'], name='job_posts_job_typ_459d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='job_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
