# Generated by Django 5.2.17 on 2026-08-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_schedule_jd_import_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='embedding_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
