# Generated by Django 5.2.17 on 2026-08-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobpost_embedding_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdimport',
            name='parse_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
