# Generated by Django 5.2.17 on 2026-08-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_repair_normalized_job_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jdimport',
            name='consumed_job',
        ),
        migrations.RemoveField(
            model_name='jdimport',
            name='file_size_bytes',
        ),
        migrations.RemoveField(
            model_name='jdimport',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='jdimport',
            name='raw_extracted_json',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='raw_extracted_json',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='raw_jd_file',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='jobskill',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='jobskill',
            name='weight',
        ),
    ]
