# Generated by Django 5.2.17 on 2026-08-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_jdimport_consumed_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='jobskill',
            name='min_years',
        ),
    ]
