# Generated by Django 5.2.17 on 2026-09-02 05:39

from django.db import migrations, models
import re
import unicodedata


def backfill_explicit_education_requirements(apps, schema_editor):
    JobPost = apps.get_model('jobs', 'JobPost')
    patterns = (
        ('NONE', (r'\bkhong (?:bat buoc|yeu cau|can)(?: co)? bang\b', r'\bdegree (?:is )?not required\b')),
        ('PHD', (r'\bph\s*\.?d\.?\b', r'\bdoctorate\b', r'\btien si\b')),
        ('MASTER', (r'\bmaster', r'\bthac si\b')),
        ('BACHELOR', (r'\bbachelor', r'\bcu nhan\b', r'\bdai hoc\b', r'\bky su\b')),
        ('ASSOCIATE', (r'\bassociate', r'\bcollege\b', r'\bcao dang\b')),
    )
    for job in JobPost.objects.filter(required_education_level__isnull=True).iterator():
        value = unicodedata.normalize('NFD', job.requirements or '')
        value = ''.join(ch for ch in value if unicodedata.category(ch) != 'Mn')
        value = value.replace('đ', 'd').replace('Đ', 'D').lower()
        level = next(
            (level for level, choices in patterns if any(re.search(pattern, value) for pattern in choices)),
            None,
        )
        if level is not None:
            job.required_education_level = level
            job.save(update_fields=['required_education_level'])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_jobpost_is_active_remove_jobskill_min_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='required_education_level',
            field=models.CharField(blank=True, choices=[('NONE', 'Không có bằng thuộc danh mục'), ('ASSOCIATE', 'Cao đẳng'), ('BACHELOR', 'Cử nhân / Kỹ sư'), ('MASTER', 'Thạc sĩ'), ('PHD', 'Tiến sĩ')], max_length=20, null=True),
        ),
        migrations.RunPython(
            backfill_explicit_education_requirements,
            migrations.RunPython.noop,
        ),
    ]
