# Generated by Django 5.2.17 on 2026-08-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_unique_company_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo_url',
        ),
    ]
