# Generated by Django 5.2.17 on 2026-08-17 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Đã ứng tuyển'), ('SHORTLISTED', 'Đã chọn lọc'), ('INTERVIEWED', 'Đã phỏng vấn'), ('REJECTED', 'Từ chối'), ('HIRED', 'Tuyển dụng')], default='APPLIED', max_length=20)),
                ('status_updated_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpost')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='candidates.resume')),
            ],
            options={
                'db_table': 'job_applications',
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('from_status', models.CharField(blank=True, choices=[('APPLIED', 'Đã ứng tuyển'), ('SHORTLISTED', 'Đã chọn lọc'), ('INTERVIEWED', 'Đã phỏng vấn'), ('REJECTED', 'Từ chối'), ('HIRED', 'Tuyển dụng')], max_length=20)),
                ('to_status', models.CharField(choices=[('APPLIED', 'Đã ứng tuyển'), ('SHORTLISTED', 'Đã chọn lọc'), ('INTERVIEWED', 'Đã phỏng vấn'), ('REJECTED', 'Từ chối'), ('HIRED', 'Tuyển dụng')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_status_changes', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.jobapplication')),
            ],
            options={
                'db_table': 'application_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status'], name='job_applica_status_6d1402_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='job_applica_job_id_e29281_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('job', 'candidate'), name='uniq_job_candidate_application'),
        ),
    ]
