# Generated by Django 5.2.17 on 2026-08-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_restrict_submitted_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstatushistory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='applicationstatushistory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='status_updated_at',
        ),
    ]
