# Generated by Django 5.2.17 on 2026-08-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_scoring_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='is_active',
        ),
    ]
