# Generated by Django 5.2.17 on 2026-09-02 05:39

from django.db import migrations, models


def initialize_match_status(apps, schema_editor):
    JobApplication = apps.get_model('applications', 'JobApplication')
    ApplicationMatchResult = apps.get_model('ai_analysis', 'ApplicationMatchResult')
    completed_ids = ApplicationMatchResult.objects.values_list('application_id', flat=True)
    JobApplication.objects.filter(pk__in=completed_ids).update(match_status='COMPLETED')
    JobApplication.objects.filter(
        profile_snapshot__isnull=True,
        match_status='PENDING',
    ).update(
        match_status='INSUFFICIENT',
        match_error='Đơn lịch sử không có snapshot tính điểm.',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_applicationstatushistory_notifications'),
        ('ai_analysis', '0006_rename_aianalysis_applicationmatchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='match_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='match_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='match_status',
            field=models.CharField(choices=[('PENDING', 'Đang chờ tính điểm'), ('PROCESSING', 'Đang tính điểm'), ('COMPLETED', 'Đã tính điểm'), ('FAILED', 'Tính điểm thất bại'), ('INSUFFICIENT', 'Chưa đủ điều kiện tính điểm')], default='PENDING', max_length=20),
        ),
        migrations.RunPython(initialize_match_status, migrations.RunPython.noop),
    ]
