# Generated by Django 5.2.17 on 2026-08-17 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semantic_similarity_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skill_overlap_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('experience_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('education_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('matched_skills', models.JSONField(blank=True, default=list, help_text='Danh sách skill trùng khớp giữa CV và JD.')),
                ('missing_skills', models.JSONField(blank=True, default=list, help_text='Skill JD yêu cầu nhưng CV không có.')),
                ('embedding_model_version', models.CharField(blank=True, max_length=100)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='applications.jobapplication')),
                ('weight_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='skills.matchingweightconfig')),
            ],
            options={
                'verbose_name_plural': 'AI analyses',
                'db_table': 'ai_analyses',
                'indexes': [models.Index(fields=['match_score'], name='ai_analyses_match_s_8f5f02_idx')],
            },
        ),
    ]
