# Generated by Django 5.2.17 on 2026-08-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0002_embedding_input_versions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aianalysis',
            name='education_score',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='experience_score',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='semantic_similarity_score',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='weight_config',
        ),
    ]
