# Generated by Django 5.2.17 on 2026-08-26 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0003_remove_aianalysis_education_score_and_more'),
        ('skills', '0004_remove_candidateskill_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='education_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='experience_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='semantic_similarity_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='weight_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='skills.matchingweightconfig'),
        ),
    ]
