# Generated by Django 5.2.17 on 2026-08-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0004_aianalysis_education_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aianalysis',
            name='candidate_embedding_version',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='computed_at',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='job_embedding_version',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='weight_config',
        ),
    ]
