# Generated by Django 5.2.17 on 2026-09-02 05:39

from django.db import migrations, models


def preserve_available_legacy_provenance(apps, schema_editor):
    ApplicationMatchResult = apps.get_model('ai_analysis', 'ApplicationMatchResult')
    for result in ApplicationMatchResult.objects.select_related('application').iterator():
        application = result.application
        weights = application.matching_weight_snapshot or {}
        original = {
            name: weights[name]
            for name in ('semantic', 'skill', 'experience', 'education')
            if name in weights
        }
        profile_snapshot = application.profile_snapshot or {}
        job_snapshot = application.job_snapshot or {}
        result.rule_version = 'legacy-v1'
        result.criteria_applicability = {
            'semantic': result.semantic_similarity_score is not None,
            'skill': result.skill_overlap_score is not None,
            'experience': result.experience_score is not None,
            'education': result.education_score is not None,
        }
        result.original_weights = original
        result.normalized_weights = original
        result.embedding_metadata = {
            'candidate_signature': profile_snapshot.get('embedding_signature'),
            'job_signature': job_snapshot.get('embedding_signature'),
            'candidate_content_version': profile_snapshot.get('profile_version'),
            'job_content_version': job_snapshot.get('content_version'),
        }
        result.save(update_fields=[
            'rule_version',
            'criteria_applicability',
            'original_weights',
            'normalized_weights',
            'embedding_metadata',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0006_rename_aianalysis_applicationmatchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmatchresult',
            name='criteria_applicability',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='applicationmatchresult',
            name='embedding_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='applicationmatchresult',
            name='missing_information',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='applicationmatchresult',
            name='normalized_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='applicationmatchresult',
            name='original_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='applicationmatchresult',
            name='rule_version',
            field=models.CharField(default='legacy-v1', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationmatchresult',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Đã tính điểm'), ('INSUFFICIENT', 'Chưa đủ điều kiện tính điểm')], default='COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationmatchresult',
            name='match_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.RunPython(
            preserve_available_legacy_provenance,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='applicationmatchresult',
            name='rule_version',
            field=models.CharField(default='matching-v2.2.4', max_length=50),
        ),
    ]
