# Generated by Django 5.2.17 on 2026-09-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0007_applicationmatchresult_criteria_applicability_and_more'),
        ('applications', '0007_jobapplication_match_attempts_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='applicationmatchresult',
            constraint=models.CheckConstraint(condition=models.Q(('match_score__isnull', True), models.Q(('match_score__gte', 0), ('match_score__lte', 100)), _connector='OR'), name='application_match_score_range'),
        ),
        migrations.AddConstraint(
            model_name='applicationmatchresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rule_version', 'matching-v2.2.4'), _negated=True), ('semantic_similarity_score__isnull', True), models.Q(('semantic_similarity_score__gte', 0), ('semantic_similarity_score__lte', 1)), _connector='OR'), name='v224_semantic_similarity_score_range'),
        ),
        migrations.AddConstraint(
            model_name='applicationmatchresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rule_version', 'matching-v2.2.4'), _negated=True), ('skill_overlap_score__isnull', True), models.Q(('skill_overlap_score__gte', 0), ('skill_overlap_score__lte', 1)), _connector='OR'), name='v224_skill_overlap_score_range'),
        ),
        migrations.AddConstraint(
            model_name='applicationmatchresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rule_version', 'matching-v2.2.4'), _negated=True), ('experience_score__isnull', True), models.Q(('experience_score__gte', 0), ('experience_score__lte', 1)), _connector='OR'), name='v224_experience_score_range'),
        ),
        migrations.AddConstraint(
            model_name='applicationmatchresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rule_version', 'matching-v2.2.4'), _negated=True), ('education_score__isnull', True), models.Q(('education_score__gte', 0), ('education_score__lte', 1)), _connector='OR'), name='v224_education_score_range'),
        ),
    ]
