# Generated by Django 5.2.17 on 2026-09-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0008_applicationmatchresult_application_match_score_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmatchresult',
            name='education_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='applicationmatchresult',
            name='experience_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='applicationmatchresult',
            name='semantic_similarity_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='applicationmatchresult',
            name='skill_overlap_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
    ]
