# Generated by Django 5.2.17 on 2026-08-17 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notif_type', models.CharField(choices=[('APPLICATION_RECEIVED', 'Nhà tuyển dụng nhận được hồ sơ mới'), ('APPLICATION_STATUS_CHANGED', 'Trạng thái ứng tuyển thay đổi'), ('COMPANY_APPROVED', 'Hồ sơ công ty được duyệt'), ('COMPANY_REJECTED', 'Hồ sơ công ty bị từ chối'), ('JOB_MATCH_SUGGESTION', 'Gợi ý việc làm phù hợp')], max_length=40)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'Trong ứng dụng')], default='EMAIL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ gửi'), ('SENT', 'Đã gửi'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Dữ liệu cấu trúc để render template email/UI.')),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='applications.jobapplication')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['status'], name='notificatio_status_fce6f5_idx')],
            },
        ),
    ]
