# Generated by Django 5.2.17 on 2026-08-17 17:35

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_enable_pgvector"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('OTHER', 'Khác')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True)),
                ('headline', models.CharField(blank=True, help_text="vd: 'Backend Developer 2 năm kinh nghiệm'", max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('desired_position', models.CharField(blank=True, max_length=255)),
                ('desired_salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Cho phép NTD tìm thấy qua Gợi ý ứng viên phù hợp')),
                ('profile_version', models.PositiveIntegerField(default=1)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('embedding_version', models.PositiveIntegerField(default=0, help_text="profile_version tại thời điểm embedding được tính, dùng để biết embedding có 'stale' hay không.")),
                ('embedding_updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'CANDIDATE'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate_profiles',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school_name', models.CharField(max_length=255)),
                ('major', models.CharField(blank=True, max_length=255)),
                ('degree', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('AI_EXTRACTED', 'AI trích xuất'), ('MANUAL', 'Nhập tay')], default='MANUAL', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidates.candidateprofile')),
            ],
            options={
                'db_table': 'candidate_educations',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('AI_EXTRACTED', 'AI trích xuất'), ('MANUAL', 'Nhập tay')], default='MANUAL', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidates.candidateprofile')),
            ],
            options={
                'db_table': 'candidate_experiences',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='resumes/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('parse_status', models.CharField(choices=[('PENDING', 'Đang xử lý'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại'), ('SKIPPED', 'Bỏ qua (nhập tay)')], default='PENDING', max_length=20)),
                ('raw_extracted_json', models.JSONField(blank=True, help_text='Output thô từ Gemini trước khi validate/normalize.', null=True)),
                ('parse_error_message', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=True, help_text='CV chính hiện dùng để ứng tuyển mặc định.')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='candidates.candidateprofile')),
            ],
            options={
                'db_table': 'resumes',
            },
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='candidate_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
