# Generated by Django 5.2.17 on 2026-08-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_unique_primary_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='embedding_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
