# Generated by Django 5.2.17 on 2026-08-21 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_resume_applied_at_resume_applied_profile_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='resume_imports/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('parse_status', models.CharField(choices=[('PENDING', 'Đang xử lý'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại'), ('CONSUMED', 'Đã dùng để cập nhật hồ sơ')], default='PENDING', max_length=20)),
                ('raw_extracted_json', models.JSONField(blank=True, help_text='Output thô từ Gemini trước khi validate/normalize.', null=True)),
                ('parsed_data', models.JSONField(blank=True, help_text='Dữ liệu đã validate, dùng để điền Form preview.', null=True)),
                ('parse_error_message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_imports', to='candidates.candidateprofile')),
            ],
            options={
                'db_table': 'resume_imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
