# Generated by Django 5.2.17 on 2026-08-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_schedule_resume_import_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parse_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeimport',
            name='parse_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
