# Generated by Django 5.2.17 on 2026-08-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_resume_parse_attempts_resumeimport_parse_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='applied_profile_version',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='parse_attempts',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='parse_error_message',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='raw_extracted_json',
        ),
        migrations.RemoveField(
            model_name='resumeimport',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='resumeimport',
            name='raw_extracted_json',
        ),
    ]
