# Generated by Django 5.2.17 on 2026-08-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_remove_education_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='desired_salary_min',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='education',
            name='source',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='source',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='parse_status',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='parsed_data',
        ),
    ]
