# Generated by Django 5.2.17 on 2026-09-02 05:39

from django.db import migrations, models


def map_known_degree_levels(apps, schema_editor):
    Education = apps.get_model('candidates', 'Education')
    patterns = (
        ('NONE', ('không có bằng', 'khong co bang', 'no degree')),
        ('PHD', ('phd', 'ph.d', 'doctorate', 'tiến sĩ', 'tien si')),
        ('MASTER', ('master', 'thạc sĩ', 'thac si')),
        ('BACHELOR', ('bachelor', 'cử nhân', 'cu nhan', 'kỹ sư', 'ky su', 'đại học', 'dai hoc')),
        ('ASSOCIATE', ('associate', 'cao đẳng', 'cao dang', 'college')),
    )
    for education in Education.objects.filter(degree_level__isnull=True).iterator():
        value = (education.degree or '').strip().lower()
        level = next(
            (level for level, aliases in patterns if any(alias in value for alias in aliases)),
            None,
        )
        if level is not None:
            education.degree_level = level
            education.save(update_fields=['degree_level'])


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_remove_candidateprofile_desired_salary_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_level',
            field=models.CharField(blank=True, choices=[('NONE', 'Không có bằng thuộc danh mục'), ('ASSOCIATE', 'Cao đẳng'), ('BACHELOR', 'Cử nhân / Kỹ sư'), ('MASTER', 'Thạc sĩ'), ('PHD', 'Tiến sĩ')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Ứng viên đã xác nhận dữ liệu học vấn này.'),
        ),
        migrations.RunPython(map_known_degree_levels, migrations.RunPython.noop),
    ]
