# Generated by Django 5.2.17 on 2026-09-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_education_degree_level_education_is_completed_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='education',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='education_valid_date_range'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.CheckConstraint(condition=models.Q(('is_current', False), ('end_date__isnull', True), _connector='OR'), name='current_experience_has_no_end'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='experience_valid_date_range'),
        ),
    ]
