# Generated by Django 5.2.17 on 2026-08-17 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'skill_categories',
            },
        ),
        migrations.CreateModel(
            name='MatchingWeightConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=False)),
                ('weight_semantic_similarity', models.DecimalField(decimal_places=3, default=0.6, max_digits=4)),
                ('weight_skill_overlap', models.DecimalField(decimal_places=3, default=0.25, max_digits=4)),
                ('weight_experience_match', models.DecimalField(decimal_places=3, default=0.1, max_digits=4)),
                ('weight_education_match', models.DecimalField(decimal_places=3, default=0.05, max_digits=4)),
                ('updated_by', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_weight_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_weight_configs',
            },
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alias_text', models.CharField(max_length=150, unique=True)),
                ('normalized_text', models.CharField(db_index=True, help_text='lower-cased / accent-stripped version used for matching.', max_length=150)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='skills.skill')),
            ],
            options={
                'db_table': 'skill_aliases',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='skills.skillcategory'),
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.CharField(blank=True, choices=[('BASIC', 'Cơ bản'), ('INTERMEDIATE', 'Trung bình'), ('ADVANCED', 'Nâng cao'), ('EXPERT', 'Chuyên gia')], max_length=20)),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('source', models.CharField(choices=[('AI_EXTRACTED', 'AI trích xuất từ CV'), ('MANUAL', 'Ứng viên tự thêm')], default='MANUAL', max_length=20)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', to='candidates.candidateprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_links', to='skills.skill')),
            ],
            options={
                'db_table': 'candidate_skills',
                'constraints': [models.UniqueConstraint(fields=('candidate', 'skill'), name='uniq_candidate_skill')],
            },
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['slug'], name='skills_slug_7d5014_idx'),
        ),
    ]
