# Generated by Django 5.2.17 on 2026-08-18 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='source',
            field=models.CharField(choices=[('CV_PARSING', 'AI phát hiện khi đọc CV'), ('JD_PARSING', 'AI phát hiện khi đọc JD'), ('ADMIN_MANUAL', 'Admin tạo tay')], default='ADMIN_MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('MERGED', 'Đã gộp vào skill khác')], default='APPROVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Admin tạm ẩn 1 skill đã APPROVED (khác với status, dùng khi cần deprecate).'),
        ),
        migrations.AlterField(
            model_name='skillalias',
            name='normalized_text',
            field=models.CharField(help_text='lower-cased / accent-stripped version, dùng để fuzzy-match (rapidfuzz) trước khi coi là skill mới hoàn toàn.', max_length=150, unique=True),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['status'], name='skills_status_c09232_idx'),
        ),
    ]
