# Generated by Django 5.2.17 on 2026-08-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_default_weight_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateskill',
            name='ai_confidence',
        ),
        migrations.RemoveField(
            model_name='candidateskill',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='skillalias',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skillalias',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='skillalias',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='updated_at',
        ),
    ]
