# Generated by Django 5.2.17 on 2026-08-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_unique_active_matching_weight_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateskill',
            name='level',
        ),
        migrations.RemoveField(
            model_name='candidateskill',
            name='source',
        ),
        migrations.RemoveField(
            model_name='candidateskill',
            name='years_of_experience',
        ),
    ]
