# Generated by Django 5.2.17 on 2026-08-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_remove_candidateskill_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='source',
        ),
    ]
