# Generated by Django 5.2.17 on 2026-09-02 05:39

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def update_untouched_default(apps, schema_editor):
    MatchingWeightConfig = apps.get_model('skills', 'MatchingWeightConfig')
    MatchingWeightConfig.objects.filter(
        name='Cấu hình mặc định',
        weight_semantic_similarity='0.600',
        weight_skill_overlap='0.250',
        weight_experience_match='0.100',
        weight_education_match='0.050',
    ).update(
        weight_semantic_similarity='0.350',
        weight_skill_overlap='0.400',
        weight_experience_match='0.200',
        weight_education_match='0.050',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_candidateskill_years_of_experience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingweightconfig',
            name='required_skill_multiplier',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='matchingweightconfig',
            name='weight_experience_match',
            field=models.DecimalField(decimal_places=3, default=0.2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='matchingweightconfig',
            name='weight_semantic_similarity',
            field=models.DecimalField(decimal_places=3, default=0.35, max_digits=4),
        ),
        migrations.AlterField(
            model_name='matchingweightconfig',
            name='weight_skill_overlap',
            field=models.DecimalField(decimal_places=3, default=0.4, max_digits=4),
        ),
        migrations.AddConstraint(
            model_name='matchingweightconfig',
            constraint=models.CheckConstraint(condition=models.Q(('weight_semantic_similarity__gte', 0), ('weight_skill_overlap__gte', 0), ('weight_experience_match__gte', 0), ('weight_education_match__gte', 0), ('weight_semantic_similarity__lte', 1), ('weight_skill_overlap__lte', 1), ('weight_experience_match__lte', 1), ('weight_education_match__lte', 1)), name='matching_weights_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='matchingweightconfig',
            constraint=models.CheckConstraint(condition=models.Q(('required_skill_multiplier__gte', 1)), name='required_skill_multiplier_gte_one'),
        ),
        migrations.RunPython(update_untouched_default, migrations.RunPython.noop),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE matching_weight_configs ADD CONSTRAINT "
                "matching_weights_sum_one CHECK ("
                "weight_semantic_similarity + weight_skill_overlap + "
                "weight_experience_match + weight_education_match = 1);"
            ),
            reverse_sql=(
                "ALTER TABLE matching_weight_configs "
                "DROP CONSTRAINT IF EXISTS matching_weights_sum_one;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE matching_weight_configs ADD CONSTRAINT "
                "required_skill_multiplier_finite CHECK ("
                "required_skill_multiplier <> 'NaN'::numeric);"
            ),
            reverse_sql=(
                "ALTER TABLE matching_weight_configs "
                "DROP CONSTRAINT IF EXISTS required_skill_multiplier_finite;"
            ),
        ),
    ]
